### ISSUE TITLE
Why button size changed on focus??

### ISSUE THREAD

**Issue by EndyKaufman** [moff/angular2-ladda#18]
![image](https://user-images.githubusercontent.com/4127109/27348217-b4c65098-560c-11e7-8cd6-5b35e5d449e1.png)

**Comment by theodorejb** [comment]
I dug into this and found that it is a bug in the Ladda library, not in the Angular wrapper. I opened hakimel/Ladda#63 to fix the issue.

It's unclear if/when a new Ladda release will have the fix, but in the meantime you can add the following CSS override to work around the issue:

```css
.ladda-button .ladda-spinner {
    height: auto;
}
```
